import { getDb } from "../api/queries/connection";
import { categories, foods, badges } from "./schema";

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // ─── Seed Categories ───
  await db.insert(categories).values([
    { name: "Grains & Breads", slug: "grains", icon: "wheat", sortOrder: 1 },
    { name: "Proteins", slug: "proteins", icon: "beef", sortOrder: 2 },
    { name: "Vegetables & Sabzi", slug: "vegetables", icon: "carrot", sortOrder: 3 },
    { name: "Lentils & Dal", slug: "lentils", icon: "bean", sortOrder: 4 },
    { name: "Dairy", slug: "dairy", icon: "milk", sortOrder: 5 },
    { name: "Rice", slug: "rice", icon: "wheat", sortOrder: 6 },
    { name: "Snacks & Sides", slug: "snacks", icon: "cookie", sortOrder: 7 },
    { name: "Beverages", slug: "beverages", icon: "cupSoda", sortOrder: 8 },
    { name: "Desserts", slug: "desserts", icon: "cake", sortOrder: 9 },
  ]);
  console.log("Categories seeded");

  // Category IDs: 1=grains, 2=proteins, 3=vegetables, 4=lentils, 5=dairy, 6=rice, 7=snacks, 8=beverages, 9=desserts

  // ─── Seed Foods ───
  await db.insert(foods).values([
    // Grains & Breads (categoryId: 1)
    {
      name: "Butter Naan", hindiName: "बटर नान",
      description: "Soft leavened bread cooked in tandoor, brushed with butter",
      image: "/butter-naan.jpg", categoryId: 1,
      servingSize: "1 piece (85g)", calories: 260,
      protein: "7.0", carbs: "38.0", fats: "9.0", fiber: "2.0", sugar: "2.5",
      isVegetarian: true, isVegan: false, isGlutenFree: false,
      mealType: "any", isPopular: true,
    },
    {
      name: "Tandoori Roti", hindiName: "तंदूरी रोटी",
      description: "Whole wheat flatbread cooked in clay tandoor",
      image: "/tandoori-roti.jpg", categoryId: 1,
      servingSize: "1 piece (40g)", calories: 120,
      protein: "4.0", carbs: "24.0", fats: "1.0", fiber: "3.0", sugar: "0.5",
      isVegetarian: true, isVegan: true, isGlutenFree: false,
      mealType: "any", isPopular: true,
    },
    {
      name: "Chapati", hindiName: "चपाती",
      description: "Whole wheat flatbread cooked on griddle",
      image: "/tandoori-roti.jpg", categoryId: 1,
      servingSize: "1 piece (30g)", calories: 80,
      protein: "3.0", carbs: "16.0", fats: "0.5", fiber: "2.0", sugar: "0.3",
      isVegetarian: true, isVegan: true, isGlutenFree: false,
      mealType: "any", isPopular: true,
    },
    {
      name: "Garlic Naan", hindiName: "गार्लिक नान",
      description: "Naan topped with garlic and coriander",
      image: "/butter-naan.jpg", categoryId: 1,
      servingSize: "1 piece (90g)", calories: 290,
      protein: "7.5", carbs: "40.0", fats: "10.0", fiber: "2.0", sugar: "2.0",
      isVegetarian: true, isVegan: false, isGlutenFree: false,
      mealType: "any", isPopular: false,
    },
    {
      name: "Ragi Dosa", hindiName: "रागी डोसा",
      description: "Crispy fermented crepe made from finger millet batter",
      image: "/ragi-dosa.jpg", categoryId: 1,
      servingSize: "1 dosa (80g)", calories: 180,
      protein: "4.5", carbs: "30.0", fats: "5.0", fiber: "3.5", sugar: "1.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "breakfast", isPopular: true,
    },
    {
      name: "Plain Dosa", hindiName: "सादा डोसा",
      description: "Thin crispy rice and lentil crepe",
      image: "/ragi-dosa.jpg", categoryId: 1,
      servingSize: "1 dosa (60g)", calories: 130,
      protein: "3.0", carbs: "25.0", fats: "2.0", fiber: "1.5", sugar: "0.5",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "breakfast", isPopular: true,
    },
    {
      name: "Idli", hindiName: "इडली",
      description: "Steamed rice and lentil cakes",
      image: "/ragi-dosa.jpg", categoryId: 1,
      servingSize: "2 pieces (80g)", calories: 100,
      protein: "3.5", carbs: "20.0", fats: "0.5", fiber: "1.5", sugar: "0.3",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "breakfast", isPopular: true,
    },

    // Proteins (categoryId: 2)
    {
      name: "Paneer Tikka", hindiName: "पनीर टिक्का",
      description: "Marinated cottage cheese cubes grilled in tandoor",
      image: "/paneer-tikka.jpg", categoryId: 2,
      servingSize: "6 pieces (120g)", calories: 280,
      protein: "18.0", carbs: "8.0", fats: "20.0", fiber: "1.0", sugar: "2.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Butter Chicken", hindiName: "बटर चिकन",
      description: "Tandoori chicken in rich tomato-butter gravy",
      image: "/butter-chicken.jpg", categoryId: 2,
      servingSize: "1 bowl (200g)", calories: 490,
      protein: "35.0", carbs: "12.0", fats: "34.0", fiber: "2.0", sugar: "5.0",
      isVegetarian: false, isVegan: false, isGlutenFree: true,
      mealType: "lunch", isPopular: true,
    },
    {
      name: "Chicken Tikka Masala", hindiName: "चिकन टिक्का मसाला",
      description: "Grilled chicken in spiced creamy tomato sauce",
      image: "/butter-chicken.jpg", categoryId: 2,
      servingSize: "1 bowl (200g)", calories: 420,
      protein: "32.0", carbs: "10.0", fats: "28.0", fiber: "2.0", sugar: "4.0",
      isVegetarian: false, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Fish Curry", hindiName: "मछली करी",
      description: "Fish cooked in aromatic coconut curry sauce",
      image: "/butter-chicken.jpg", categoryId: 2,
      servingSize: "1 bowl (180g)", calories: 310,
      protein: "28.0", carbs: "6.0", fats: "18.0", fiber: "1.0", sugar: "1.5",
      isVegetarian: false, isVegan: false, isGlutenFree: true,
      mealType: "lunch", isPopular: false,
    },
    {
      name: "Tandoori Chicken", hindiName: "तंदूरी चिकन",
      description: "Chicken marinated in yogurt and spices, cooked in tandoor",
      image: "/paneer-tikka.jpg", categoryId: 2,
      servingSize: "2 pieces (150g)", calories: 280,
      protein: "35.0", carbs: "4.0", fats: "13.0", fiber: "0.5", sugar: "1.0",
      isVegetarian: false, isVegan: false, isGlutenFree: true,
      mealType: "dinner", isPopular: true,
    },
    {
      name: "Paneer Bhurji", hindiName: "पनीर भुर्जी",
      description: "Scrambled cottage cheese with onions and spices",
      image: "/palak-paneer.jpg", categoryId: 2,
      servingSize: "1 bowl (150g)", calories: 320,
      protein: "22.0", carbs: "8.0", fats: "24.0", fiber: "1.5", sugar: "3.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },
    {
      name: "Egg Curry", hindiName: "एंडा करी",
      description: "Hard-boiled eggs in spiced tomato-onion gravy",
      image: "/chole-masala.jpg", categoryId: 2,
      servingSize: "2 eggs + gravy (200g)", calories: 290,
      protein: "18.0", carbs: "10.0", fats: "20.0", fiber: "2.0", sugar: "3.0",
      isVegetarian: false, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },

    // Vegetables & Sabzi (categoryId: 3)
    {
      name: "Aloo Gobi", hindiName: "आलू गोभी",
      description: "Potato and cauliflower dry curry with turmeric",
      image: "/aloo-gobi.jpg", categoryId: 3,
      servingSize: "1 bowl (150g)", calories: 180,
      protein: "4.0", carbs: "22.0", fats: "9.0", fiber: "5.0", sugar: "3.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Bhindi Masala", hindiName: "भिंडी मसाला",
      description: "Stir-fried okra with onions and spices",
      image: "/aloo-gobi.jpg", categoryId: 3,
      servingSize: "1 bowl (150g)", calories: 150,
      protein: "3.5", carbs: "18.0", fats: "7.0", fiber: "6.0", sugar: "4.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Mixed Vegetable Sabzi", hindiName: "मिक्स सब्जी",
      description: "Seasonal vegetables cooked with Indian spices",
      image: "/aloo-gobi.jpg", categoryId: 3,
      servingSize: "1 bowl (150g)", calories: 140,
      protein: "4.0", carbs: "16.0", fats: "6.0", fiber: "5.0", sugar: "5.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },
    {
      name: "Baingan Bharta", hindiName: "बैंगन भरता",
      description: "Smoky mashed roasted eggplant with spices",
      image: "/aloo-gobi.jpg", categoryId: 3,
      servingSize: "1 bowl (150g)", calories: 130,
      protein: "3.0", carbs: "14.0", fats: "7.0", fiber: "5.0", sugar: "4.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },
    {
      name: "Aloo Jeera", hindiName: "आलू जीरा",
      description: "Cumin-spiced potato stir-fry",
      image: "/aloo-gobi.jpg", categoryId: 3,
      servingSize: "1 bowl (150g)", calories: 200,
      protein: "3.0", carbs: "28.0", fats: "9.0", fiber: "3.0", sugar: "2.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Gobi Manchurian", hindiName: "गोभी मंचूरियन",
      description: "Crispy cauliflower in tangy Indo-Chinese sauce",
      image: "/aloo-gobi.jpg", categoryId: 3,
      servingSize: "1 bowl (180g)", calories: 280,
      protein: "6.0", carbs: "30.0", fats: "15.0", fiber: "4.0", sugar: "8.0",
      isVegetarian: true, isVegan: false, isGlutenFree: false,
      mealType: "snack", isPopular: true,
    },

    // Lentils & Dal (categoryId: 4)
    {
      name: "Dal Makhani", hindiName: "दाल मखनी",
      description: "Creamy black lentils slow-cooked with butter and cream",
      image: "/dal-makhani.jpg", categoryId: 4,
      servingSize: "1 bowl (200g)", calories: 320,
      protein: "14.0", carbs: "30.0", fats: "16.0", fiber: "8.0", sugar: "3.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Yellow Dal Tadka", hindiName: "दाल तड़का",
      description: "Yellow lentils tempered with cumin, garlic, and chili",
      image: "/dal-makhani.jpg", categoryId: 4,
      servingSize: "1 bowl (200g)", calories: 180,
      protein: "10.0", carbs: "25.0", fats: "5.0", fiber: "6.0", sugar: "2.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Chole Masala", hindiName: "छोले मसाला",
      description: "Spicy chickpea curry with aromatic spices",
      image: "/chole-masala.jpg", categoryId: 4,
      servingSize: "1 bowl (200g)", calories: 280,
      protein: "12.0", carbs: "38.0", fats: "9.0", fiber: "10.0", sugar: "4.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Rajma Masala", hindiName: "राजमा मसाला",
      description: "Red kidney bean curry with onions and tomatoes",
      image: "/rajma-chawal.jpg", categoryId: 4,
      servingSize: "1 bowl (200g)", calories: 260,
      protein: "13.0", carbs: "35.0", fats: "8.0", fiber: "11.0", sugar: "3.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "lunch", isPopular: true,
    },
    {
      name: "Moong Dal", hindiName: "मूंग दाल",
      description: "Split yellow mung lentils, light and easy to digest",
      image: "/dal-makhani.jpg", categoryId: 4,
      servingSize: "1 bowl (200g)", calories: 150,
      protein: "10.0", carbs: "22.0", fats: "3.0", fiber: "5.0", sugar: "1.5",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Sambar", hindiName: "सांभर",
      description: "South Indian lentil and vegetable stew with tamarind",
      image: "/ragi-dosa.jpg", categoryId: 4,
      servingSize: "1 bowl (200g)", calories: 130,
      protein: "6.0", carbs: "20.0", fats: "3.0", fiber: "5.0", sugar: "3.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },

    // Dairy (categoryId: 5)
    {
      name: "Palak Paneer", hindiName: "पालक पनीर",
      description: "Cottage cheese cubes in creamy spinach gravy",
      image: "/palak-paneer.jpg", categoryId: 5,
      servingSize: "1 bowl (200g)", calories: 310,
      protein: "18.0", carbs: "12.0", fats: "22.0", fiber: "4.0", sugar: "3.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Paneer Butter Masala", hindiName: "पनीर बटर मसाला",
      description: "Cottage cheese in rich tomato-cream gravy",
      image: "/palak-paneer.jpg", categoryId: 5,
      servingSize: "1 bowl (200g)", calories: 380,
      protein: "16.0", carbs: "14.0", fats: "28.0", fiber: "2.0", sugar: "6.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Raita", hindiName: "रायता",
      description: "Yogurt with cucumber, cumin, and herbs",
      image: "/mango-lassi.jpg", categoryId: 5,
      servingSize: "1 bowl (100g)", calories: 80,
      protein: "4.0", carbs: "6.0", fats: "4.0", fiber: "0.5", sugar: "4.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Shahi Paneer", hindiName: "शाही पनीर",
      description: "Cottage cheese in royal creamy cashew gravy",
      image: "/palak-paneer.jpg", categoryId: 5,
      servingSize: "1 bowl (200g)", calories: 350,
      protein: "16.0", carbs: "12.0", fats: "26.0", fiber: "1.5", sugar: "5.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },
    {
      name: "Kadhi Pakora", hindiName: "कढ़ी पकोड़ा",
      description: "Gram flour yogurt curry with fritters",
      image: "/mango-lassi.jpg", categoryId: 5,
      servingSize: "1 bowl (200g)", calories: 240,
      protein: "10.0", carbs: "24.0", fats: "12.0", fiber: "3.0", sugar: "5.0",
      isVegetarian: true, isVegan: false, isGlutenFree: false,
      mealType: "lunch", isPopular: false,
    },

    // Rice (categoryId: 6)
    {
      name: "Jeera Rice", hindiName: "जीरा राइस",
      description: "Fragrant basmati rice tempered with cumin seeds",
      image: "/jeera-rice.jpg", categoryId: 6,
      servingSize: "1 bowl (150g)", calories: 210,
      protein: "4.0", carbs: "42.0", fats: "3.0", fiber: "1.0", sugar: "0.5",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Dal Chawal", hindiName: "दाल चावल",
      description: "Steamed basmati rice served with yellow dal tadka",
      image: "/dal-makhani.jpg", categoryId: 6,
      servingSize: "1 plate (350g)", calories: 380,
      protein: "11.0", carbs: "65.0", fats: "8.0", fiber: "7.0", sugar: "1.5",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "lunch", isPopular: true,
    },
    {
      name: "Veg Biryani", hindiName: "वेज बिरयानी",
      description: "Fragrant rice layered with vegetables and spices",
      image: "/veg-biryani.jpg", categoryId: 6,
      servingSize: "1 plate (250g)", calories: 380,
      protein: "8.0", carbs: "55.0", fats: "14.0", fiber: "5.0", sugar: "4.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "lunch", isPopular: true,
    },
    {
      name: "Curd Rice", hindiName: "दही चावल",
      description: "Yogurt mixed with rice and tempered spices",
      image: "/jeera-rice.jpg", categoryId: 6,
      servingSize: "1 bowl (200g)", calories: 250,
      protein: "7.0", carbs: "38.0", fats: "7.0", fiber: "1.0", sugar: "3.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Lemon Rice", hindiName: "नींबू चावल",
      description: "Tangy rice with lemon, peanuts, and curry leaves",
      image: "/jeera-rice.jpg", categoryId: 6,
      servingSize: "1 bowl (150g)", calories: 220,
      protein: "5.0", carbs: "35.0", fats: "7.0", fiber: "2.0", sugar: "1.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },
    {
      name: "Pulao", hindiName: "पुलाव",
      description: "Mixed vegetable rice with whole spices",
      image: "/veg-biryani.jpg", categoryId: 6,
      servingSize: "1 bowl (200g)", calories: 280,
      protein: "6.0", carbs: "45.0", fats: "8.0", fiber: "3.0", sugar: "2.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },

    // Snacks & Sides (categoryId: 7)
    {
      name: "Samosa", hindiName: "समोसा",
      description: "Crispy pastry filled with spiced potatoes and peas",
      image: "/aloo-gobi.jpg", categoryId: 7,
      servingSize: "2 pieces (100g)", calories: 310,
      protein: "5.0", carbs: "36.0", fats: "16.0", fiber: "3.0", sugar: "2.0",
      isVegetarian: true, isVegan: true, isGlutenFree: false,
      mealType: "snack", isPopular: true,
    },
    {
      name: "Pakora", hindiName: "पकोड़ा",
      description: "Mixed vegetable fritters in gram flour batter",
      image: "/aloo-gobi.jpg", categoryId: 7,
      servingSize: "4 pieces (80g)", calories: 220,
      protein: "5.0", carbs: "22.0", fats: "12.0", fiber: "4.0", sugar: "3.0",
      isVegetarian: true, isVegan: true, isGlutenFree: false,
      mealType: "snack", isPopular: true,
    },
    {
      name: "Papad", hindiName: "पापड़",
      description: "Crispy lentil wafer, roasted or fried",
      image: "/butter-naan.jpg", categoryId: 7,
      servingSize: "1 piece (10g)", calories: 40,
      protein: "2.0", carbs: "6.0", fats: "1.0", fiber: "1.0", sugar: "0.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },
    {
      name: "Coconut Chutney", hindiName: "नारियल चटनी",
      description: "Fresh coconut chutney with curry leaves and mustard seeds",
      image: "/ragi-dosa.jpg", categoryId: 7,
      servingSize: "2 tbsp (30g)", calories: 60,
      protein: "1.0", carbs: "4.0", fats: "5.0", fiber: "2.0", sugar: "2.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Vada", hindiName: "वड़ा",
      description: "Savory fried lentil doughnut, crispy outside and soft inside",
      image: "/ragi-dosa.jpg", categoryId: 7,
      servingSize: "2 pieces (80g)", calories: 240,
      protein: "6.0", carbs: "28.0", fats: "12.0", fiber: "3.0", sugar: "1.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "snack", isPopular: true,
    },

    // Beverages (categoryId: 8)
    {
      name: "Mango Lassi", hindiName: "आम लस्सी",
      description: "Refreshing yogurt drink with mango pulp",
      image: "/mango-lassi.jpg", categoryId: 8,
      servingSize: "1 glass (250ml)", calories: 180,
      protein: "6.0", carbs: "28.0", fats: "5.0", fiber: "1.0", sugar: "24.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Masala Chai", hindiName: "मसाला चाय",
      description: "Spiced tea with milk, cardamom, ginger, and cinnamon",
      image: "/mango-lassi.jpg", categoryId: 8,
      servingSize: "1 cup (200ml)", calories: 120,
      protein: "4.0", carbs: "14.0", fats: "5.0", fiber: "0.5", sugar: "10.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Sweet Lassi", hindiName: "मीठी लस्सी",
      description: "Sweetened yogurt drink with cardamom",
      image: "/mango-lassi.jpg", categoryId: 8,
      servingSize: "1 glass (250ml)", calories: 150,
      protein: "6.0", carbs: "22.0", fats: "5.0", fiber: "0.5", sugar: "18.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: false,
    },
    {
      name: "Nimbu Pani", hindiName: "निम्बू पानी",
      description: "Indian lemonade with cumin and mint",
      image: "/mango-lassi.jpg", categoryId: 8,
      servingSize: "1 glass (250ml)", calories: 45,
      protein: "0.5", carbs: "11.0", fats: "0.2", fiber: "0.5", sugar: "9.0",
      isVegetarian: true, isVegan: true, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Filter Coffee", hindiName: "फिल्टर कॉफी",
      description: "South Indian style coffee with frothy milk",
      image: "/mango-lassi.jpg", categoryId: 8,
      servingSize: "1 cup (150ml)", calories: 80,
      protein: "3.0", carbs: "8.0", fats: "4.0", fiber: "0.0", sugar: "6.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "breakfast", isPopular: true,
    },

    // Desserts (categoryId: 9)
    {
      name: "Gulab Jamun", hindiName: "गुलाब जामुन",
      description: "Deep-fried milk solids soaked in fragrant sugar syrup",
      image: "/gulab-jamun.jpg", categoryId: 9,
      servingSize: "2 pieces (60g)", calories: 280,
      protein: "4.0", carbs: "42.0", fats: "11.0", fiber: "0.5", sugar: "35.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "snack", isPopular: true,
    },
    {
      name: "Rasgulla", hindiName: "रसगुल्ला",
      description: "Soft cottage cheese balls in light sugar syrup",
      image: "/gulab-jamun.jpg", categoryId: 9,
      servingSize: "2 pieces (80g)", calories: 160,
      protein: "5.0", carbs: "28.0", fats: "3.0", fiber: "0.0", sugar: "24.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "snack", isPopular: true,
    },
    {
      name: "Kheer", hindiName: "खीर",
      description: "Rice pudding cooked with milk, nuts, and cardamom",
      image: "/gulab-jamun.jpg", categoryId: 9,
      servingSize: "1 bowl (150g)", calories: 220,
      protein: "6.0", carbs: "30.0", fats: "8.0", fiber: "0.5", sugar: "22.0",
      isVegetarian: true, isVegan: false, isGlutenFree: true,
      mealType: "any", isPopular: true,
    },
    {
      name: "Jalebi", hindiName: "जलेबी",
      description: "Crispy spiral soaked in saffron sugar syrup",
      image: "/gulab-jamun.jpg", categoryId: 9,
      servingSize: "3 pieces (60g)", calories: 250,
      protein: "2.0", carbs: "42.0", fats: "8.0", fiber: "0.5", sugar: "30.0",
      isVegetarian: true, isVegan: true, isGlutenFree: false,
      mealType: "snack", isPopular: true,
    },
    {
      name: "Halwa", hindiName: "हलवा",
      description: "Semolina pudding with ghee, nuts, and raisins",
      image: "/gulab-jamun.jpg", categoryId: 9,
      servingSize: "1 bowl (100g)", calories: 320,
      protein: "4.0", carbs: "38.0", fats: "16.0", fiber: "1.5", sugar: "20.0",
      isVegetarian: true, isVegan: false, isGlutenFree: false,
      mealType: "any", isPopular: false,
    },
  ]);
  console.log("Foods seeded");

  // ─── Seed Badges ───
  await db.insert(badges).values([
    {
      name: "First Log", description: "Log your first meal",
      icon: "utensils", color: "#c2410c",
      requirementType: "meals_logged", requirementValue: 1, points: 10,
    },
    {
      name: "Daily Tracker", description: "Log meals for 3 consecutive days",
      icon: "calendar-check", color: "#15803d",
      requirementType: "streak_days", requirementValue: 3, points: 25,
    },
    {
      name: "Streak Master", description: "Maintain a 7-day logging streak",
      icon: "flame", color: "#ea580c",
      requirementType: "streak_days", requirementValue: 7, points: 50,
    },
    {
      name: "Scanner Pro", description: "Scan 5 different foods",
      icon: "scan", color: "#7c3aed",
      requirementType: "scans", requirementValue: 5, points: 30,
    },
    {
      name: "Thali Builder", description: "Create your first thali with 4+ items",
      icon: "plate", color: "#c2410c",
      requirementType: "thali_items", requirementValue: 4, points: 20,
    },
    {
      name: "Health Hero", description: "Stay under calorie goal for 5 days",
      icon: "heart", color: "#dc2626",
      requirementType: "calorie_goal_days", requirementValue: 5, points: 40,
    },
    {
      name: "Protein Champion", description: "Hit protein goal 3 days in a row",
      icon: "dumbbell", color: "#2563eb",
      requirementType: "protein_goal_days", requirementValue: 3, points: 35,
    },
    {
      name: "Explorer", description: "Try 10 different foods",
      icon: "compass", color: "#0891b2",
      requirementType: "unique_foods", requirementValue: 10, points: 25,
    },
    {
      name: "Veggie Lover", description: "Log 15 vegetarian meals",
      icon: "leaf", color: "#16a34a",
      requirementType: "veg_meals", requirementValue: 15, points: 30,
    },
    {
      name: "Month Master", description: "Log meals for 30 days total",
      icon: "trophy", color: "#ca8a04",
      requirementType: "total_days", requirementValue: 30, points: 100,
    },
  ]);
  console.log("Badges seeded");

  console.log("Seed complete!");
}

seed().catch(console.error);
